import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { 
  QueryClient, 
  QueryClientProvider 
} from '@tanstack/react-query';

import "./globals.css";
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient()

export const metadata: Metadata = {
  title: "Job Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider client={queryClient}>
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <Toaster/>
            {children}
          </body>
        </html>
      </ClerkProvider>
    </QueryClientProvider>
  );
}
